In [2]:
import pandas as pd 
import torch 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch.nn as nn
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("enhanced_anxiety_dataset.csv")
df.head(3)

Age  Gender Occupation  Sleep Hours  Physical Activity (hrs/week)  \
0   29  Female     Artist          6.0                           2.7   
1   46   Other      Nurse          6.2                           5.7   
2   64    Male      Other          5.0                           3.7   

   Caffeine Intake (mg/day)  Alcohol Consumption (drinks/week) Smoking  \
0                       181                                 10     Yes   
1                       200                                  8     Yes   
2                       117                                  4      No   

  Family History of Anxiety  Stress Level (1-10)  Heart Rate (bpm)  \
0                        No                   10               114   
1                       Yes                    1                62   
2                       Yes                    1                91   

   Breathing Rate (breaths/min)  Sweating Level (1-5) Dizziness Medication  \
0                            14                     4        No        Yes   
1                            23                     2       Yes         No   
2                            28                     3        No         No   

   Therapy Sessions (per month) Recent Major Life Event  Diet Quality (1-10)  \
0                             3                     Yes                    7   
1                             2                      No                    8   
2                             1                     Yes                    1   

   Anxiety Level (1-10)  
0                   5.0  
1                   3.0  
2                   1.0

In [4]:
df = df.drop(columns=['Therapy Sessions (per month)'])

In [5]:
df.head(2)

Age  Gender Occupation  Sleep Hours  Physical Activity (hrs/week)  \
0   29  Female     Artist          6.0                           2.7   
1   46   Other      Nurse          6.2                           5.7   

   Caffeine Intake (mg/day)  Alcohol Consumption (drinks/week) Smoking  \
0                       181                                 10     Yes   
1                       200                                  8     Yes   

  Family History of Anxiety  Stress Level (1-10)  Heart Rate (bpm)  \
0                        No                   10               114   
1                       Yes                    1                62   

   Breathing Rate (breaths/min)  Sweating Level (1-5) Dizziness Medication  \
0                            14                     4        No        Yes   
1                            23                     2       Yes         No   

  Recent Major Life Event  Diet Quality (1-10)  Anxiety Level (1-10)  
0                     Yes                    7                   5.0  
1                      No                    8                   3.0

In [6]:
dummies = pd.get_dummies(df , columns=['Gender','Occupation' ,'Smoking' , 'Dizziness' ,'Medication' ,'Recent Major Life Event' ,'Family History of Anxiety' ]).astype(int)

In [7]:
dummies.head(2)

Age  Sleep Hours  Physical Activity (hrs/week)  Caffeine Intake (mg/day)  \
0   29            6                             2                       181   
1   46            6                             5                       200   

   Alcohol Consumption (drinks/week)  Stress Level (1-10)  Heart Rate (bpm)  \
0                                 10                   10               114   
1                                  8                    1                62   

   Breathing Rate (breaths/min)  Sweating Level (1-5)  Diet Quality (1-10)  \
0                            14                     4                    7   
1                            23                     2                    8   

   ...  Smoking_No  Smoking_Yes  Dizziness_No  Dizziness_Yes  Medication_No  \
0  ...           0            1             1              0              0   
1  ...           0            1             0              1              1   

   Medication_Yes  Recent Major Life Event_No  Recent Major Life Event_Yes  \
0               1                           0                            1   
1               0                           1                            0   

   Family History of Anxiety_No  Family History of Anxiety_Yes  
0                             1                              0  
1                             0                              1  

[2 rows x 37 columns]

In [8]:
num_cols = df.drop(columns=['Gender','Occupation' ,'Smoking' , 'Dizziness' ,'Medication' ,'Recent Major Life Event' ,'Family History of Anxiety' ])

In [9]:
df = pd.concat([dummies , num_cols] , axis=1)

In [10]:
df.head(2)

Age  Sleep Hours  Physical Activity (hrs/week)  Caffeine Intake (mg/day)  \
0   29            6                             2                       181   
1   46            6                             5                       200   

   Alcohol Consumption (drinks/week)  Stress Level (1-10)  Heart Rate (bpm)  \
0                                 10                   10               114   
1                                  8                    1                62   

   Breathing Rate (breaths/min)  Sweating Level (1-5)  Diet Quality (1-10)  \
0                            14                     4                    7   
1                            23                     2                    8   

   ...  Sleep Hours  Physical Activity (hrs/week)  Caffeine Intake (mg/day)  \
0  ...          6.0                           2.7                       181   
1  ...          6.2                           5.7                       200   

   Alcohol Consumption (drinks/week)  Stress Level (1-10)  Heart Rate (bpm)  \
0                                 10                   10               114   
1                                  8                    1                62   

   Breathing Rate (breaths/min)  Sweating Level (1-5)  Diet Quality (1-10)  \
0                            14                     4                    7   
1                            23                     2                    8   

   Anxiety Level (1-10)  
0                   5.0  
1                   3.0  

[2 rows x 48 columns]

In [11]:
x= df.iloc[:,:-1]
y = df.iloc[:,-1]

In [12]:
scaled = StandardScaler()
x = scaled.fit_transform(x)

In [13]:
x

array([[-0.84935927, -0.16093441, -0.27111965, ..., -1.34839473,
         0.65724526,  0.62801793],
       [ 0.43506146, -0.16093441,  1.3651182 , ...,  0.39583427,
        -0.77253777,  0.9734278 ],
       [ 1.79503636, -0.95513741,  0.27429296, ...,  1.36485039,
        -0.05764625, -1.44444125],
       ...,
       [-0.84935927, -0.16093441,  1.91053081, ..., -0.96078829,
        -1.48742928,  0.62801793],
       [ 0.96394059, -0.95513741, -0.27111965, ...,  1.36485039,
        -0.05764625, -1.09903139],
       [ 1.19060307, -0.16093441, -0.81653227, ..., -1.54219795,
        -0.05764625,  0.9734278 ]])

In [14]:
labled = LabelEncoder()
y = labled.fit_transform(y)

In [15]:
y

array([4, 2, 0, ..., 3, 3, 1], dtype=int64)

In [16]:
x = torch.from_numpy(x).float()
y = torch.from_numpy(y).float()

In [17]:
import torch
import torch.nn as nn

class Model(nn.Module):  
    def __init__(self, num_feature):  
        super(Model, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(num_feature, 5),
            nn.ReLU(),
            nn.Linear(5, 1),
            nn.Sigmoid()
        )

    def forward(self, features): 
        output = self.network(features)
        return output


In [18]:
model = Model(x.shape[1])

In [19]:
model.forward(x)

tensor([[0.4671],
        [0.4171],
        [0.4374],
        ...,
        [0.5463],
        [0.4939],
        [0.4822]], grad_fn=<SigmoidBackward0>)

In [20]:
model.network[0].weight

Parameter containing:
tensor([[-0.0398, -0.1176,  0.0194, -0.0662,  0.1077, -0.0344, -0.0231, -0.0802,
          0.0710, -0.1020, -0.1227, -0.0906,  0.0629,  0.1167, -0.1175,  0.0500,
          0.1074,  0.1070,  0.0440, -0.0880,  0.0877,  0.0828,  0.0637,  0.0854,
          0.0391,  0.0684,  0.1318, -0.0131, -0.0248,  0.1066, -0.1017, -0.0588,
          0.0524, -0.0046, -0.1327, -0.0625, -0.0023, -0.0050,  0.0644, -0.0129,
         -0.0332,  0.0613,  0.1294, -0.0348, -0.0549, -0.0791,  0.0661],
        [ 0.0781,  0.0817, -0.0059, -0.1455,  0.0456,  0.1439,  0.0229, -0.0832,
         -0.0825, -0.0170, -0.0678,  0.1429,  0.0498, -0.0444,  0.0564, -0.0533,
          0.0316,  0.0327, -0.1450,  0.0558, -0.0740, -0.0270,  0.1154, -0.0103,
          0.0299, -0.0758,  0.1085,  0.1250,  0.0462, -0.0227,  0.1084,  0.0167,
          0.1071, -0.1087, -0.1074,  0.0922,  0.0904,  0.0123, -0.0130, -0.1450,
          0.0236, -0.0833,  0.0892, -0.1202,  0.0173,  0.0220,  0.1312],
        [-0.0644,  0.0

In [27]:
from torchinfo import summary
summary(model, input_size=(10, x.shape[1]))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 5]                   240
│    └─ReLU: 2-2                         [10, 5]                   --
│    └─Linear: 2-3                       [10, 1]                   6
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 246
Trainable params: 246
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00