In [2]:
from sklearn.datasets import make_classification
import torch

In [3]:
x,y = make_classification(

    n_features=2,n_samples=10,random_state=42,n_informative=2 , n_redundant=0 , n_classes=2 
)

In [4]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [6]:
type(x)

numpy.ndarray

In [7]:
len(y)

10

In [8]:
feature = torch.from_numpy(x).float()
label   = torch.from_numpy(y).float()

In [9]:
from torch.utils.data import Dataset , DataLoader

In [10]:
class Mydataset(Dataset):
    def __init__(self , feature , lable):
        self.feature= feature
        self.lable = lable
    def __len__(self): 
        return len(self.feature)
    def __getitem__(self ,index): 
        return self.feature[index] , self.lable[index]

In [11]:
dataset = Mydataset(feature , label)

In [12]:
len(dataset)

10

In [13]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1.))

In [14]:
loader = DataLoader(dataset , batch_size=2 ,shuffle=False)

In [15]:
for batch_feature1 , batch_lable1 in loader:
    print(batch_feature1)
    print(batch_lable1)
    print('------'* 50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1., 0.])
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0., 0.])
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0., 1.])
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Using_Pytorch Dataset and DataLoader in nn Module Pipeline

In [17]:
import pandas as pd 
import numpy as np 
import torch 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [19]:
df.head(2)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0  842302         M        17.99         10.38           122.8     1001.0   
1  842517         M        20.57         17.77           132.9     1326.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33            184.6      2019.0            0.1622   
1  ...          23.41            158.8      1956.0            0.1238   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  

[2 rows x 33 columns]

In [20]:
df = df.drop(columns=['id', 'Unnamed: 32'])

In [21]:
df.head(2)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38           122.8     1001.0   
1         M        20.57         17.77           132.9     1326.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6   
1         0.1812  ...         24.99          23.41            158.8   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 31 columns]

In [22]:
x_train , x_test , y_train , y_test = train_test_split(df.iloc[:,1:] , df.iloc[:,0] , random_state=42 , test_size=0.2)

In [23]:
scale = StandardScaler()
x_train = scale.fit_transform(x_train)
x_test = scale.fit_transform(x_test)

In [24]:
Label = LabelEncoder()
y_train = Label.fit_transform(y_train)
y_test  = Label.fit_transform(y_test)

In [25]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [26]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [27]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [28]:
x_train_tensor.shape

torch.Size([455, 30])

In [29]:
from torch.utils.data import Dataset , DataLoader

In [30]:
class MyDataset:
    def __init__(self , feature , lable):
        self.feature = feature
        self.feature = lable
    def __len__(self):
        return len(self.feature)
    def __getitem__(self , index):
        return self.feature[index] , self.lable[index]

In [31]:
train_data = Mydataset(x_train_tensor , y_train_tensor)
test_data = Mydataset(x_test_tensor , y_test_tensor)

In [32]:
train_Loader = DataLoader(train_data , shuffle=False , batch_size=32)
test_Loader = DataLoader(test_data , shuffle=False , batch_size=32)

In [33]:
import torch.nn as nn

In [34]:
class MyNN(nn.Module):
    def __init__(self , num_feature):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_feature , 5),
            nn.ReLU(),
            nn.Linear(5 , 1),
            nn.Sigmoid()  
        )
        
    def forward(self , feature):
        output = self.network(feature)
        return output
        

In [35]:
learning_rate = 0.1
epochs = 25

In [36]:
model = MyNN(x_train_tensor.shape[1])

In [37]:
from torch.optim import SGD

In [38]:
optimizer = SGD(model.parameters() , lr=learning_rate)

In [39]:
loss_funtion = nn.BCELoss()

In [48]:
for epoch in range(epochs):
    for batch_feature , batch_lable in train_Loader:
        y_pred = model(batch_feature)
        loss =loss_funtion(y_pred , batch_lable.view(-1,1))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.012223437428474426
Epoch: 2, Loss: 0.011809145100414753
Epoch: 3, Loss: 0.01143344584852457
Epoch: 4, Loss: 0.011110269464552402
Epoch: 5, Loss: 0.010816489346325397
Epoch: 6, Loss: 0.010543703101575375
Epoch: 7, Loss: 0.010289950296282768
Epoch: 8, Loss: 0.010057913139462471
Epoch: 9, Loss: 0.009835979901254177
Epoch: 10, Loss: 0.009629943408071995
Epoch: 11, Loss: 0.009435362182557583
Epoch: 12, Loss: 0.00925144087523222
Epoch: 13, Loss: 0.009074928238987923
Epoch: 14, Loss: 0.008910051546990871
Epoch: 15, Loss: 0.008753480389714241
Epoch: 16, Loss: 0.008603033609688282
Epoch: 17, Loss: 0.008463512174785137
Epoch: 18, Loss: 0.008328520692884922
Epoch: 19, Loss: 0.008202367462217808
Epoch: 20, Loss: 0.0080858850851655
Epoch: 21, Loss: 0.00797000341117382
Epoch: 22, Loss: 0.007857060991227627
Epoch: 23, Loss: 0.007755058351904154
Epoch: 24, Loss: 0.007659133058041334
Epoch: 25, Loss: 0.007571198511868715


In [52]:
model.eval()  
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_Loader:
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9766
