In [2]:
import torch 

In [3]:
a = torch.eye(3,3)

In [4]:
a

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [5]:
type(a)

torch.Tensor

In [6]:
b  = torch.tensor([2. , 2 , 2])

In [7]:
b

tensor([2., 2., 2.])

In [8]:
c = a*b

In [9]:
c

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])

In [10]:
def sqare(x):
    return x**2

In [11]:
sqare(3)

9

In [26]:
x = torch.tensor(3.0 , requires_grad=True)

In [28]:
x

tensor(3., requires_grad=True)

In [30]:
y = x**2

In [36]:
y.backward()

In [38]:
x.grad

tensor(6.)

In [44]:
x1 = torch.tensor(4., requires_grad=True)
y1 =  x1**2
y1.backward()
x1.grad

tensor(8.)

In [48]:
x2 = torch.zeros(2,2  , requires_grad=True)

In [52]:
y3 = x**2

In [54]:
y3.backward()

In [60]:
import math

In [62]:
def sq(x):
    return 2*math.cos(x**2)

In [64]:
sq(3)

-1.8222605237693539

In [72]:
x = torch.tensor(5.0 ,requires_grad=True)
y= x**2
z = torch.sin(y)
z.backward()
("value of derivative of y wrt to x is " , x.grad)
("value of derivative of z wrt to y is " , y.grad)

C:\Users\Zeshan\AppData\Local\Temp\ipykernel_3840\3006407464.py:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  ("value of derivative of z wrt to y is " , y.grad)


('value of derivative of z wrt to y is ', None)

----------------------------------------------

In [83]:
x = torch.tensor(3.5)
y = torch.tensor(0.0)
w= torch.tensor(2.5 , requires_grad=True)
b = torch.tensor(5.5 , requires_grad=True)
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))
# Forward pass
z = w * x + b  # Weighted sum (linear part)
y_pred = torch.sigmoid(z)  # Predicted probability

# Compute binary cross-entropy loss
loss = binary_cross_entropy_loss(y_pred, y)
loss.backward()

print("Gradient w.r.t w:", w.grad)
print("Gradient w.r.t b:", b.grad)


Gradient w.r.t w: tensor(3.5000)
Gradient w.r.t b: tensor(1.0000)


In [79]:
z = w*x1+b

In [ ]:
z